### PR TITLE
Allow support for redirects, which are defined in the src folder

### PR DESCRIPTION
**Pull request by graywolf336**

### CODE REVIEW

**Review by sampaiodiego — COMMENTED** [review]
should we test if `./src/redirects.json` exists before requiring it? I'm not able to test what happens if it doesn't exists

**Comment by graywolf336** [comment]
Yeah I'll add that, although it should exist so that we start getting a better user experience for when we move files around.

**Comment by graywolf336** [comment]
@sampaiodiego This is ready to be reviewed whenever you get a chance.

**Review by sampaiodiego — APPROVED** [review]
I think we need to improve how Senna works with redirects from links, but it looks good to me

**Pull request merged**
